import { spawn, type ChildProcess } from "node:child_process"
import { existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { setTimeout as sleep } from "node:timers/promises"

export interface CmdConfig {
  model?: string
  reasoning?: string
  permissionMode?: "safe" | "yolo"
  /** Session mode: normal (default) or plan (read-only, --plan). */
  mode?: "normal" | "plan"
  /** Resume a previous Command Code session (--resume <sessionId>). */
  resumeSessionId?: string
}

/** A tool the agent has queued for execution. */
export interface CmdToolQueued {
  type: "tool_queued"
  /** Stable id generated by Command Code (e.g. `call_<32 hex>`). */
  toolCallId: string
  toolName: string
  input?: unknown
}

/**
 * A tool that was refused.
 *
 * Two wire shapes exist across Command Code releases:
 *   - `tool_hook_blocked` (pre-1.53): carries `hookOutput` with the refusal text
 *   - `tool_denied` (1.53+): carries no reason at all
 *
 * Both are normalised to this shape, so callers never branch on the version.
 */
export interface CmdToolDenied {
  type: "tool_denied"
  toolCallId: string
  toolName: string
  /** Refusal text, when the release provided one. */
  reason?: string
}

/** Raw `tool_hook_blocked` payload (pre-1.53 releases). */
interface RawToolHookBlocked {
  type: "tool_hook_blocked"
  toolCallId?: string
  toolName?: string
  hookOutput?: string
}

/** Incremental reasoning output (`thinking_delta.delta`). */
export interface CmdThinkingDelta {
  type: "thinking_delta"
  delta?: string
}

/**
 * Normalise a refusal event into {@link CmdToolDenied}.
 *
 * Returns null when the payload lacks the identifiers needed to correlate it
 * with a tool call: emitting a denial without an id would leave the client
 * unable to resolve the matching `tool_call`.
 */
export function normalizeToolDenied(event: {
  type?: unknown
  toolCallId?: unknown
  id?: unknown
  toolName?: unknown
  hookOutput?: unknown
  message?: unknown
  reason?: unknown
}): CmdToolDenied | null {
  const toolCallId = event.toolCallId ?? event.id
  const toolName = event.toolName
  if (typeof toolCallId !== "string" || !toolCallId) return null
  if (typeof toolName !== "string" || !toolName) return null

  const reason = event.hookOutput ?? event.message ?? event.reason
  return {
    type: "tool_denied",
    toolCallId,
    toolName,
    ...(typeof reason === "string" && reason ? { reason } : {}),
  }
}

export interface CmdEvent {
  type: "event"
  event: CmdToolQueued | CmdToolDenied | CmdThinkingDelta | { type: string; [key: string]: unknown }
}

export interface CmdUsage {
  totalTokens?: number
  inputTokens?: number
  outputTokens?: number
  cacheReadTokens?: number
  cacheWriteTokens?: number
}

export interface CmdResult {
  type: "result"
  subtype: "success" | "error" | "max_turns"
  sessionId?: string
  stopReason?: string
  finalText?: string
  error?: string
  usage?: CmdUsage | null
}

export type CmdLine = CmdEvent | CmdResult

export interface CmdRunOutcome {
  /** Raw final text from Command Code (may be empty on error). */
  finalText: string
  /** Tools observed in the event stream, in order. */
  tools: (CmdToolQueued | CmdToolDenied)[]
  stopReason: "end_turn" | "max_turns" | "error" | "cancelled"
  /** Present when subtype === "error". */
  error?: string
  /** sessionId from the result frame, when present. */
  cmdSessionId?: string
  /** Token usage from the result frame, when present. */
  usage?: CmdUsage
}

/**
 * Resolve the `cmd` binary name: CMD_BIN env override, then `cmd` on PATH.
 *
 * Kept for compatibility; runtime spawning uses {@link resolveCmdSpawn}, which
 * handles the Windows case where a bare `cmd` resolves to `C:\Windows\System32\cmd.exe`.
 */
export function resolveCmdBinary(): string {
  const override = process.env.CMD_BIN?.trim()
  if (override) return override
  return "cmd"
}

/** How to launch Command Code: a command plus arguments that must precede ours. */
export interface CmdSpawn {
  command: string
  argsPrefix: string[]
}

/**
 * Locate the Command Code ESM entry (`command-code/dist/index.mjs`).
 *
 * `CMD_ENTRY` answers this on every platform. Failing that, Windows needs a
 * heuristic: npm only installs `.cmd` shims there, which cannot be launched
 * with `CreateProcess` (Node's non-shell `spawn` fails with ENOENT), while a
 * bare `cmd` resolves to the OS `cmd.exe` instead of Command Code. Everywhere
 * else the shim is executable, so the PATH fallback in {@link resolveCmdSpawn}
 * is the better answer and no guess is made here.
 */
function findCommandCodeEntry(): string | undefined {
  const fromEnv = process.env.CMD_ENTRY?.trim()
  if (fromEnv && existsSync(fromEnv)) return fromEnv

  if (process.platform !== "win32") return undefined

  // Global install alongside the running Node runtime.
  const sibling = join(
    dirname(process.execPath),
    "node_modules",
    "command-code",
    "dist",
    "index.mjs",
  )
  if (existsSync(sibling)) return sibling

  return undefined
}

/**
 * Resolve how to spawn Command Code.
 *
 * On Windows, when the entry can be located, returns `process.execPath` plus the
 * entry as a prefix argument, so the ESM entry is executed directly. Arguments
 * stay in an array (never a shell string), so user prompt text cannot be
 * interpreted by a shell.
 */
export function resolveCmdSpawn(): CmdSpawn {
  const override = process.env.CMD_BIN?.trim()
  if (override) {
    // An explicit .js/.mjs path is executed with the current Node runtime.
    if (/\.m?js$/.test(override)) {
      return { command: process.execPath, argsPrefix: [override] }
    }
    return { command: override, argsPrefix: [] }
  }

  const entry = findCommandCodeEntry()
  if (entry) return { command: process.execPath, argsPrefix: [entry] }

  if (process.platform === "win32") {
    process.stderr.write(
      "[cmd-acp] warning: Command Code entry not found; falling back to 'cmd' on PATH " +
        "(on Windows this may resolve to C:\\Windows\\System32\\cmd.exe). " +
        "Set CMD_ENTRY to command-code/dist/index.mjs to fix this.\n",
    )
  }

  return { command: resolveCmdBinary(), argsPrefix: [] }
}

/**
 * Run a single headless Command Code prompt and stream its NDJSON frames.
 * One `cmd -p --output-format json` process per call (fire-and-forget).
 */
export async function runCmdPrompt(opts: {
  prompt: string
  cwd: string
  config?: CmdConfig
  signal?: AbortSignal
  /** When set, Command Code asks this broker before running sensitive tools. */
  brokerAddress?: string
  /** Passed through so the broker can bind a decision to a session. */
  sessionId?: string
  onTool?: (tool: CmdToolQueued) => void
  onToolDenied?: (tool: CmdToolDenied) => void
  onThought?: (delta: string) => void
  onText?: (text: string) => void
}): Promise<CmdRunOutcome> {
  const {
    prompt,
    cwd,
    config = {},
    signal,
    brokerAddress,
    sessionId,
    onTool,
    onToolDenied,
    onThought,
    onText,
  } = opts

  const args = ["-p", prompt, "--output-format", "json"]
  if (config.model) args.push("--model", config.model)
  if (config.reasoning) args.push("--effort", config.reasoning)
  if (config.permissionMode === "yolo") args.push("--yolo")
  if (config.mode === "plan") args.push("--plan")
  if (config.resumeSessionId) args.push("--resume", config.resumeSessionId)

  const { command, argsPrefix } = resolveCmdSpawn()
  const child = spawn(command, [...argsPrefix, ...args], {
    cwd,
    env: {
      ...process.env,
      // Consumed by the patched permission gate. Absent means Command Code
      // keeps its built-in fail-closed behaviour.
      ...(brokerAddress ? { CMD_ACP_PERMISSION_BROKER: brokerAddress } : {}),
      ...(sessionId ? { COMMAND_CODE_SESSION: sessionId } : {}),
    },
    stdio: ["ignore", "pipe", "pipe"],
    // Windows gives every child its own console window unless told otherwise.
    // One turn spawns one Command Code process, so without this a conversation
    // flashes a black window on every prompt. Pipes are unaffected.
    windowsHide: true,
  })
  if (!child.stdout || !child.stderr) {
    throw new Error("Failed to spawn cmd: missing stdio streams")
  }

  const abortHandler = () => {
    child.kill("SIGINT")
  }
  signal?.addEventListener("abort", abortHandler, { once: true })

  let buffered = ""
  const tools: (CmdToolQueued | CmdToolDenied)[] = []
  let finalText = ""
  let stopReason: CmdRunOutcome["stopReason"] = "end_turn"
  let error: string | undefined
  let cmdSessionId: string | undefined
  let usage: CmdUsage | undefined

  const stderr: string[] = []

  function handleLine(line: string) {
    if (!line.trim()) return
    let parsed: CmdLine
    try {
      parsed = JSON.parse(line) as CmdLine
    } catch {
      // Forward-compatible: ignore non-JSON lines on stdout.
      return
    }
    if (parsed.type === "event") {
      const event = parsed.event
      if (!event || typeof event.type !== "string") return
      // Unknown event types are ignored so new Command Code releases cannot
      // break the bridge.
      switch (event.type) {
        case "tool_queued": {
          const tool = event as CmdToolQueued
          tools.push(tool)
          onTool?.(tool)
          break
        }
        case "tool_denied":
        case "tool_hook_blocked": {
          const denied = normalizeToolDenied(event as Record<string, unknown>)
          if (denied) {
            tools.push(denied)
            onToolDenied?.(denied)
          }
          break
        }
        case "thinking_delta": {
          const delta = (event as CmdThinkingDelta).delta
          if (typeof delta === "string" && delta) onThought?.(delta)
          break
        }
      }
      return
    }
    if (parsed.type === "result") {
      if (parsed.sessionId) cmdSessionId = parsed.sessionId
      if (parsed.usage) usage = parsed.usage
      if (parsed.subtype === "error") {
        stopReason = "error"
        error = parsed.error ?? "Command Code returned an error"
      } else if (parsed.subtype === "max_turns") {
        stopReason = "max_turns"
      }
      if (parsed.finalText) {
        finalText = parsed.finalText
        onText?.(parsed.finalText)
      }
    }
  }

  child.stdout.setEncoding("utf8")
  child.stdout.on("data", (chunk: string) => {
    buffered += chunk
    let nl: number
    while ((nl = buffered.indexOf("\n")) >= 0) {
      const line = buffered.slice(0, nl)
      buffered = buffered.slice(nl + 1)
      handleLine(line)
    }
  })
  child.stderr.setEncoding("utf8")
  child.stderr.on("data", (chunk: string) => {
    stderr.push(chunk)
  })

  let exitCode: number | null = null
  try {
    const [code] = await Promise.all([
      new Promise<number>((resolve, reject) => {
        child.on("error", reject)
        child.on("exit", (c) => {
          exitCode = c ?? 0
          resolve(c ?? 0)
        })
      }),
      sleep(0),
    ])
    if (signal?.aborted) {
      return { finalText, tools, stopReason: "cancelled", cmdSessionId, usage }
    }
    if ((stopReason as string) === "error") {
      const stderrText = stderr.join("").trim()
      const fallback = `cmd exited with code ${code}`
      return {
        finalText,
        tools,
        stopReason,
        error: error ?? (stderrText || fallback),
        cmdSessionId,
        usage,
      }
    }
    // Handle nonzero exit / unparsed failure (e.g. auth error EXIT_AUTH_ERROR=3).
    if (exitCode !== 0 && !finalText && tools.length === 0) {
      const stderrText = stderr.join("").trim()
      return {
        finalText: "",
        tools,
        stopReason: "error",
        error: stderrText || `cmd exited with code ${exitCode}`,
        cmdSessionId,
        usage,
      }
    }
    return { finalText, tools, stopReason, cmdSessionId, usage }
  } finally {
    signal?.removeEventListener("abort", abortHandler)
  }
}
